config/routes.rb
BrainCandySolution::Application.routes.draw do
  devise_for :users

  root :to => "home#index"

  resources :brain_candies do
    member do
      post :claim_complete
      post :verify
    end
  end

end

app/models/brain_candy.rb
class BrainCandy < ActiveRecord::Base
  attr_accessible :name, :difficulty_level_id, :photo

  belongs_to :difficulty_level
  has_many :brain_candy_completions, dependent: :destroy

  delegate :name, to: :difficulty_level, prefix: true, allow_nil: true
  delegate :url, to: :photo, prefix: true, allow_nil: true

  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  validates_presence_of :name
  validates_uniqueness_of :name, case_sensitive: false
end

app/models/brain_candy_completion.rb
class BrainCandyCompletion < ActiveRecord::Base
  belongs_to :brain_candy
  belongs_to :user
  belongs_to :verifying_user
  attr_accessible :completed_at, :victory_text, :brain_candy

  def self.status(object)
    return :unsolved unless object.present?
    object.status
  end

  def status
    verifying_user_id.present? ? :solved : :claimed
  end
end

app/models/difficulty_level.rb
class DifficultyLevel < ActiveRecord::Base
  attr_accessible :name
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :brain_candy_completions, dependent: :destroy
  has_many :brain_candies, through: :brain_candy_completions

  def candy_status(candy)
    @candy_lookup ||= Hash[brain_candy_completions.map { |bcc| [bcc.brain_candy_id, bcc] }]
    BrainCandyCompletion.status @candy_lookup[candy.id]
  end

  def claim_complete(candy)
    brain_candy_completions << BrainCandyCompletion.new(brain_candy: candy) unless has_candy?(candy.id)
  end

  # self should be the verifying user
  def verify(candy, claiming_user_id)
    bcc = BrainCandyCompletion.find_by_brain_candy_id_and_user_id(candy.id, claiming_user_id)
    bcc.update_column :verifying_user_id, self.id
  end

  private

  def has_candy?(candy_id)
    brain_candy_completions.select { |bcc| bcc.brain_candy_id == candy_id }.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate_user!
end

app/controllers/brain_candies_controller.rb
class BrainCandiesController < ApplicationController
  before_filter :find_brain_candy, only: [:show, :edit, :update, :destroy, :claim_complete, :verify]

  # GET /brain_candies
  # GET /brain_candies.json
  def index
    @brain_candies = BrainCandy.includes(:difficulty_level).all

    respond_to do |format|
      format.html # index.html.erb.erb
      format.json { render json: @brain_candies }
    end
  end

  # GET /brain_candies/1
  # GET /brain_candies/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @brain_candy }
    end
  end

  # GET /brain_candies/new
  # GET /brain_candies/new.json
  def new
    @brain_candy = BrainCandy.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @brain_candy }
    end
  end

  # GET /brain_candies/1/edit
  def edit
  end

  # POST /brain_candies
  # POST /brain_candies.json
  def create
    @brain_candy = BrainCandy.new(params[:brain_candy])

    respond_to do |format|
      if @brain_candy.save
        format.html { redirect_to @brain_candy, notice: 'Brain candy was successfully created.' }
        format.json { render json: @brain_candy, status: :created, location: @brain_candy }
      else
        format.html { render action: "new" }
        format.json { render json: @brain_candy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /brain_candies/1
  # PUT /brain_candies/1.json
  def update
    respond_to do |format|
      if @brain_candy.update_attributes(params[:brain_candy])
        format.html { redirect_to @brain_candy, notice: 'Brain candy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @brain_candy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brain_candies/1
  # DELETE /brain_candies/1.json
  def destroy
    @brain_candy.destroy

    respond_to do |format|
      format.html { redirect_to brain_candies_url }
      format.json { head :no_content }
    end
  end

  def claim_complete
    current_user.claim_complete(@brain_candy)
    redirect_to :root
  end

  # user_id
  def verify
    user_id = params[:user_id]
    raise "user_id must be provided" unless user_id
    raise "Stop hacking me" if current_user.id == user_id

    current_user.verify @brain_candy, user_id
    redirect_to :root
  end

  private

  def find_brain_candy
    @brain_candy = BrainCandy.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @brain_candies = BrainCandy.all
    @users = User.includes(:brain_candy_completions).all

    # Finding the current_user object with preloaded brain_candy_completions
    @current_user = @users.select{|u| u.id == current_user.id}.first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def home_link
    return nil if controller_name == "home"
    link_to("Home", :root) + " | "
  end
end

app/helpers/brain_candies_helper.rb
module BrainCandiesHelper
  def brain_candy_photo
    image_tag @brain_candy.photo_url(:medium) if @brain_candy.photo.present?
  end

  def show_candy_status(status)
    label =
        {unsolved: nil,
         solved: {text: "Solved", label: "label-success"},
         claimed: {text: "Claimed", label: "label-warning"}}[status]

    return nil unless label.present?
    content_tag :span, label[:text], class: "label #{label[:label]}"
  end
end

app/views/brain_candies/_form.html.erb
<%= bootstrap_form_for(@brain_candy, html: {multipart: true}) do |f| %>
    <%= f.alert_message "Please fix the errors below." %>
    <%= f.text_field :name %>
    <%= f.select :difficulty_level_id, DifficultyLevel.all.map { |dl| [dl.name, dl.id] }, label: "Difficulty" %>

    <p><%= brain_candy_photo %></p>

    <%= f.file_field :photo, label: :none %>

    <%= f.actions do %>
        <%= f.primary "Submit", disable_with: 'Working...' %>
    <% end %>
<% end %>

app/views/brain_candies/edit.html.erb
<h1>Editing Brain Candy</h1>

<%= render 'form' %>

<%= link_to 'Show', @brain_candy %> |
<%= link_to 'Back', brain_candies_path %>

app/views/brain_candies/index.html.erb
<h1>Listing Brain Candies</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Difficulty level</th>
    <th></th>
  </tr>

  <% @brain_candies.each do |brain_candy| %>
      <tr>
        <td><%= brain_candy.name %></td>
        <td><%= brain_candy.difficulty_level_name %></td>
        <td>
          <%= link_to 'Show', brain_candy %>&nbsp;&nbsp;
          <%= link_to 'Edit', edit_brain_candy_path(brain_candy) %>&nbsp;&nbsp;
          <%= link_to 'Destroy', brain_candy, method: :delete, data: {confirm: 'Are you sure?'} %>
        </td>
      </tr>
  <% end %>
</table>

<br/>

<%= link_to 'New Brain candy', new_brain_candy_path, class: "btn" %>

app/views/brain_candies/new.html.erb
<h1>New Brain Candy</h1>

<%= render 'form' %>

<%= link_to 'Back', brain_candies_path %>

app/views/brain_candies/show.html.erb
<p>
  <b>Name:</b>
  <%= @brain_candy.name %>
</p>

<p>
  <b>Difficulty level:</b>
  <%= @brain_candy.difficulty_level_name %>
</p>

<p><%= brain_candy_photo %></p>

<%= link_to 'Edit', edit_brain_candy_path(@brain_candy) %> |
<%= link_to 'Back', brain_candies_path %>

app/views/home/_completions.html.erb
<table class="table table-bordered">
  <thead>
  <tr>
    <th></th>
    <th>Name</th>
    <% @users.each do |u| %>
        <th><%= u.email %></th>
    <% end %>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @brain_candies.each do |bc| %>
      <tr>
        <td><%= image_tag bc.photo.url(:thumb) %></td>
        <td><%= bc.name %></td>
        <% @users.each do |u| %>
            <td>
              <%= show_candy_status u.candy_status(bc) %>
              <%= link_to "Verify!", verify_brain_candy_path(bc, user_id: u.id), method: :post, class: "pull-right" if u.candy_status(bc) == :claimed and u != current_user %>
            </td>
        <% end %>
        <td><%= link_to "I did it!", claim_complete_brain_candy_path(bc), method: :post if @current_user.candy_status(bc) == :unsolved %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/home/index.html.erb
<h1>Brain Candies!</h1>

<p>
  <%= render partial: "completions" %>
</p>

app/views/layouts/_login_header.html.erb
<p>
  <nav class="pull-right">
    <% if user_signed_in? %>
        <%= link_to("Home", :root) %> |
        <%= link_to "Manage candies", :brain_candies %> |
        <%= content_tag :span, current_user.email %> |
        <%= content_tag :span, link_to("Sign out", :destroy_user_session, method: :delete) %>
    <% end %>
  </nav>
  <div class="clearfix"></div>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "BrainCandySolution" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>
</head>
<body>

<div class="container">
  <%= render partial: "layouts/login_header" %>
  <div class="row">
    <div class="span12">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
  </div>
  <!--/row-->

  <footer>
    <p>&copy; BrainCandies, Inc 2013</p>
  </footer>

</div>
<!-- /container -->

<!-- Javascripts
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<%= javascript_include_tag "application" %>

</body>
</html>

app/views/layouts/application_old.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BrainCandySolution</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: "layouts/login_header" %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>